# server configuration
server.httpsPort: 8436
server.serviceId: com.networknt.controller-1.0.0

# client.yml
client.verifyHostname: false

# controller configuration
controller.clusterMode: true
controller.bootstrapToken: eyJraWQiOiIxMDAiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ1cm46Y29tOm5ldHdvcmtudDpvYXV0aDI6djEiLCJhdWQiOiJ1cm46Y29tLm5ldHdvcmtudCIsImV4cCI6MTk2MDMwOTk4MywianRpIjoiSllkbExici16Qm8tOF9sb3RyODNQdyIsImlhdCI6MTY0NDk0OTk4MywibmJmIjoxNjQ0OTQ5ODYzLCJ2ZXJzaW9uIjoiMS4wIiwiY2xpZW50X2lkIjoiZjdkNDIzNDgtYzY0Ny00ZWZiLWE1MmQtNGM1Nzg3NDIxZTczIiwic2NvcGUiOlsicG9ydGFsLnIiLCJwb3J0YWwudyJdfQ.rhwozi6h2RxxYFECS0xusuZLui9STpKP-tipnTSTKU45EXP5k_OBXUWiTJ9m30yFC_GC6vY5gRgHprjCx0s2dOERZXf4xxsolHJ0jkqZuBoxyemqHsIeo5grJahZps58cz6m_kj9IMoG9uReVLYSIwjTprURSAWORGCOOCuzS7v4JG_iGA9fFs2hkA06pifAcu-UGJTbGlkjff6FgJExPTLHXUwsxcmAm1CMCPleRl38wUINbPXtOMCaJ_nb3wyZwYAoYkc2dGDry01lRCW0jj0P_1xykv_OCzebq7r3pz48ZDdmXRCeQYWTfHGentX2C-Gn5HCz9TW205LYuLYaJg

# producer format configuration
kafka-producer.bootstrap.servers: localhost:9093
kafka-producer.schema.registry.url: http://localhost:8081

# streams configuration
kafka-streams.bootstrap.servers: localhost:9093
kafka-streams.schema.registry.url: http://localhost:8081
kafka-streams.application.id: light-controller
kafka-streams.cleanUp: false

#rule-loader
ruleLoader.enabled: true
ruleLoader.portalHost: https://localhost:8442

# access-control
accessControl.enabled: true

# service
service.singletons:
  - com.networknt.cache.CacheManager:
      - com.networknt.cache.CaffeineCacheManager
  # StartupHookProvider implementations, there are one to many, and they are called in the same sequence defined.
  - com.networknt.server.StartupHookProvider:
      - com.networknt.controller.ControllerStartupHook
      - com.networknt.rule.RuleLoaderStartupHook

  # ShutdownHookProvider implementations, there are one to many, and they are called in the same sequence defined.
  - com.networknt.server.ShutdownHookProvider:
      - com.networknt.controller.ControllerShutdownHook
  - com.networknt.kafka.producer.NativeLightProducer:
      - com.networknt.kafka.producer.SidecarProducer
  - io.confluent.kafka.schemaregistry.client.SchemaRegistryClient:
      - com.networknt.kafka.common.LightSchemaRegistryClient

# handler.yml
handler.handlers:
  # Light-framework cross-cutting concerns implemented in the microservice
  - com.networknt.exception.ExceptionHandler@exception
  - com.networknt.metrics.MetricsHandler@metrics
  - com.networknt.traceability.TraceabilityHandler@traceability
  - com.networknt.correlation.CorrelationHandler@correlation
  - com.networknt.openapi.OpenApiHandler@specification
  - com.networknt.openapi.JwtVerifyHandler@security
  - com.networknt.body.BodyHandler@body
  - com.networknt.audit.AuditHandler@audit
  # DumpHandler is to dump detail request/response info to log, useful for troubleshooting but not suggested to use in production due to it may lower the performance
  # - com.networknt.dump.DumpHandler@dump
  - com.networknt.sanitizer.SanitizerHandler@sanitizer
  - com.networknt.openapi.ValidatorHandler@validator
  # Customer business domain specific cross-cutting concerns handlers
  # - com.example.validator.CustomizedValidator@custvalidator
  # Framework endpoint handlers
  - com.networknt.health.HealthGetHandler@health
  - com.networknt.info.ServerInfoGetHandler@info
  - com.networknt.chaos.KillappAssaultHandler@killapp
  - com.networknt.chaos.LatencyAssaultHandler@latency
  - com.networknt.chaos.MemoryAssaultHandler@memory
  - com.networknt.chaos.ExceptionAssaultHandler@exchaos
  - com.networknt.chaos.ChaosMonkeyGetHandler@chaosget
  - com.networknt.chaos.ChaosMonkeyPostHandler@chaospost
  - com.networknt.logging.handler.LoggerGetHandler@getLogger
  - com.networknt.logging.handler.LoggerPostHandler@postLogger
  - com.networknt.specification.SpecDisplayHandler@spec
  - com.networknt.specification.SpecSwaggerUIHandler@swaggerui
  - com.networknt.specification.FaviconHandler@favicon

  # - com.networknt.metrics.prometheus.PrometheusGetHandler@getprometheus
  # Business Middleware Handlers
  - com.networknt.openapi.AccessControlHandler@access
  # Business Handlers
  - com.networknt.controller.handler.ServicesPostHandler
  - com.networknt.controller.handler.ServicesDeleteHandler
  - com.networknt.controller.handler.ServicesGetHandler
  - com.networknt.controller.handler.ServicesLookupGetHandler
  - com.networknt.controller.handler.ServicesCheckGetHandler
  - com.networknt.controller.handler.ServicesCheckPutHandler
  - com.networknt.controller.handler.ServicesCheckIdGetHandler
  - com.networknt.controller.handler.ServicesInfoNodeGetHandler
  - com.networknt.controller.handler.WebSocketHandler
  - com.networknt.controller.handler.ServicesLoggerGetHandler
  - com.networknt.controller.handler.ServicesLoggerPostHandler
  - com.networknt.controller.handler.ServicesLoggerContentPostHandler
  - com.networknt.controller.handler.ServicesChaosMonkeyGetHandler
  - com.networknt.controller.handler.ServicesChaosMonkeyPostHandler
  - com.networknt.controller.handler.ServicesChaosMonkeyAssaultPostHandler
  - com.networknt.controller.handler.ServicesModuleGetHandler
  - com.networknt.controller.handler.ServicesModulePostHandler
  - com.networknt.controller.handler.ServicesShutdownPostHandler


handler.chains.default:
  - exception
  # - metrics
  - traceability
  - correlation
  - killapp
  - latency
  - memory
  - exchaos
  - specification
  - security
  - body
  - audit
  - sanitizer
  - validator
  - access

# cache.yml
cache.caches:
  - cacheName: jwt
    expiryInMinutes: 15
    maxSize: 100
  - cacheName: jwk
    expiryInMinutes: 129600
    maxSize: 100
